# Base image for Streamlit app with Python 3.11
FROM python:3.11-slim

# Install dependencies
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy Streamlit app files
COPY ds_article_rag ./ds_article_rag

RUN mkdir ./data

# Expose Streamlit port
EXPOSE 8501

# Run streamlit app
CMD ["streamlit", "run", "ds_article_rag/app.py", "--server.port", "8501", "--server.address", "0.0.0.0"]
